name: Compile SerialPort Bindings

on: [push]

jobs:
  build:
    name: Compile ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1.2.0
        with:
          node-version: "12"

      - name: Install Windows Build Tools
        if: matrix.os == 'windows-latest'
        run: |
          npm install -g node-gyp

      - name: Install Dependencies
        run: |
          npm install --ignore-scripts
          npm install serialport node-abi
          npm install npx

      - name: Rebuild Bindings
        uses: ./.github/actions/compile-modules-action
        with:
          git-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Bindings
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-node${{ matrix.node }}-modules
          path: ./native_modules
